title: Pench3r
author: Pench3r
email: nageshangzei@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Developer | Hacker
baseurl: 
twitter_username: ang
github_username:  pench3r
disqus:
    shortname: pench3r

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
